config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'breakout', to: 'pages#breakout', as: :breakout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candle_collection.rb
class CandleCollection
  def initialize(candle_dumps)
    @candle_dumps = candle_dumps
  end

  def chart_data
    @chart_data ||= candle_dumps
                      .sort_by(&:occurred_at)
                      .map { |cd| { cd.occurred_at.utc.strftime("[%d-%m] [%I:%M %p]") => cd.price.to_f } }
                      .reduce({}, :merge)
  end

  def should_buy?
    last_consecutive_actions[0] > 1 &&
      last_consecutive_actions[1] > 0.5
  end

  def starting_price
    @starting_price ||= candle_dumps.min_by(&:occurred_at).price
  end

  def ending_price
    @ending_price ||= candle_dumps.max_by(&:occurred_at).price
  end

  def difference
    ((ending_price - starting_price)*100.00/starting_price)
      .round(3)
  end

  def minimum_price
    @minimum_price ||= candle_dumps.minimum(:price)
  end

  def candle_pairs
    result = []
    candle_dumps.sort_by(&:occurred_at).each_cons(2) do |first, second|
      result << CandlePair.new(first, second)
    end
    result
  end

  def last_consecutive_actions
    @last_consecutive_actions ||= calculate_last_consecutive_actions
  end

  private

  attr_reader :candle_dumps

  def calculate_last_consecutive_actions
    total_diff = 0
    action_count = 0
    candle_dumps.sort_by(&:occurred_at).reverse!.each_cons(2) do |first, second|
      current_diff = change(second, first).to_f.round(3)

      next if current_diff.zero?

      if current_diff.negative?
        if total_diff.negative? || total_diff.zero?
          action_count += 1
          total_diff += current_diff
        else
          return action_count, total_diff
        end
      else
        if total_diff.negative?
          return action_count, total_diff
        else
          action_count += 1
          total_diff += current_diff
        end
      end
    end

    [action_count, total_diff]
  end

  def change(cd1, cd2)
    ((cd2.price - cd1.price) * 100.00 / cd1.price).round(3)
  end
end

app/models/candle_dump.rb
class CandleDump < ApplicationRecord
  belongs_to :wallet
end

app/models/candle_pair.rb
class CandlePair
  def initialize(candle_one, candle_two)
    @candle_one = candle_one
    @candle_two = candle_two
  end

  def change
    @change ||= ((candle_two.price - candle_one.price)*100.00 / candle_one.price)
      .round(3)
  end

  def start_time
    format_time(candle_one.occurred_at)
  end

  def end_time
    format_time(candle_two.occurred_at)
  end

  def closing_price
    candle_two.price
  end

  private

  attr_reader :candle_one,
              :candle_two

  def format_time(timestamp)
    timestamp.utc.strftime("%d %b, %I:%M %p")
  end
end

app/models/coindcx_client.rb
class CoindcxClient
  class << self
    API_SECRET         = "196b9d88bc773ad9e941d660151bde2cb348329191892ba3761e4f126f152c61"
    API_KEY            = "dd6eece30f0e2efe44319731be071cd2d9a8b02ba1d1e656"
    GET_BALANCE_URL    = "https://api.coindcx.com/exchange/v1/users/balances"
    MARKET_DETAILS_URL = "https://api.coindcx.com/exchange/v1/markets_details"
    CANDLE_URL         = "https://public.coindcx.com/market_data/candles"

    def user_balances
      body = body_with_timestamp

      JSON.parse(Excon.post(
        GET_BALANCE_URL,
        body: body,
        headers: authenticated_headers(body)
      ).body, symbolize_names: true)
    end

    def market_details
      JSON.parse(Excon.get(MARKET_DETAILS_URL).body, symbolize_names: true)
    end

    def candles(pair)
      JSON.parse(Excon.get(CANDLE_URL, query: { pair: pair, interval: '1m', startTime: 1624125720000 }).body, symbolize_names: true)
    end

    private

    def body_with_timestamp
      {
        "timestamp" => Time.now.to_i
      }.to_json
    end

    def authenticated_headers(payload)
      signature = OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), API_SECRET, payload)

      {
        'Content-Type' => 'application/json',
        'X-AUTH-APIKEY' => API_KEY,
        'X-AUTH-SIGNATURE' => signature
      }
    end
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  has_many :candle_dumps, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def breakout
    if params[:wallet_id].present? &&
      params[:start_time].present? &&
      params[:end_time].present?
      @data = CandleDump.where(wallet_id: params[:wallet_id]).where("occurred_at AT TIME ZONE 'UTC' >= ? and occurred_at AT TIME ZONE 'UTC' <= ?", params[:start_time], params[:end_time])
      @candle_collection = CandleCollection.new(@data)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def starting_price(candle_dumps)
    candle_dumps.min_by(&:occurred_at).price
  end

  def ending_price(candle_dumps)
    candle_dumps.max_by(&:occurred_at).price
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cryptoraider</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/breakout.html.erb
<h1>
  Predict Breakout
</h1>
<%= form_tag(breakout_path, method: :get) do %>
  <div>
    <%= label_tag :wallet %>
    <%= select_tag :wallet_id, options_from_collection_for_select(Wallet.all, 'id', 'currency', params[:wallet_id]) %>
  </div>
  <br/>
  <div>
    <%= label_tag :start_time %>
    <%= datetime_field_tag :start_time, params[:start_time] %>
  </div>
  <br/>
  <div>
    <%= label_tag :end_time %>
    <%= datetime_field_tag :end_time, params[:end_time] %>
  </div>
  <%= submit_tag :search %>
<% end %>
<% if @data.present? %>
  <h2>Stats</h2>
  <p>
    <b>Starting Price</b> <%= @candle_collection.starting_price %><br/>
    <b>Ending Price</b> <%= @candle_collection.ending_price %><br/>
    <b>Difference</b> <%= @candle_collection.difference %> %<br/>
  </p>
  <p>
    <b>
      Recent Changes
    </b><br/>
    <% @candle_collection.candle_pairs.each do |candle_pair| %>
      <% unless candle_pair.change.zero? %>
        <b>Changed</b>
        <span class=<%= candle_pair.change.positive? ? "text-success" : "text-danger" %>>
          <%= candle_pair.change %> %
        </span>
        <b>between</b> <%= candle_pair.start_time %> and <%= candle_pair.end_time %>
        <b>Closed at: </b><%= candle_pair.closing_price %><br/>
      <% end %>
    <% end %>
    <span class=<%= @candle_collection.should_buy? ? "text-success" : "text-danger" %>>
      <%= @candle_collection.should_buy? ? "YES BUY IT" : "NO DON'T BUY IT" %><br/>
    </span>
  </p>
  <h2>Trend</h2>
  <%= line_chart(@candle_collection.chart_data,
                 precision: 5,
                 min: @candle_collection.minimum_price, discrete: true) %>
<% end %>

app/views/pages/home.html.erb
<% Wallet.includes(:candle_dumps).find_each do |wallet| %>
  <%= "Stats for #{wallet.currency}" %>
  <%= line_chart(CandleCollection.new(wallet.candle_dumps).chart_data,
                 precision: 5,
                 min: CandleCollection.new(wallet.candle_dumps).minimum_price)%>
<% end %>